---
- hosts: jenkins
  become: yes
  gather_facts: no

  tasks:
    - name: Copy Jenkins jobs into place.
      copy:
        src: #S3 bucket
        dest: /var/lib/jenkins #jenkins config folder
      notify: restart jenkins
      become: yes
      become_user: jenkins
      tags: ['jenkins']
