---
- name: Update apt-get repo and cache
  apt: update_cache=yes force_apt_get=yes cache_valid_time=3600
  become: true

- name: Upgrade all apt packages
  apt: upgrade=dist force_apt_get=yes
  become: true

- name: Ensure dependencies are installed.
  apt:
    name:
      - curl
      - apt-transport-https
      - gnupg
    state: present
  become: true

#- name: Include vars of plugin_list.yml into the 'jenkins_plugins' variable.
#  include_vars:
#    file: plugin_list.yml
#    name: jenkins_plugins

- name: Install Java 8 using apt.
  apt:
    name: "{{java.VERSION}}"
    state: latest  
  become: true

- name: Add Jenkins apt repository key.
  apt_key:
    url: "{{ jenkins_repo_key_url }}"
    state: present

- name: Add Jenkins apt repository.
  apt_repository:
    repo: "{{ jenkins_repo_url }}"
    state: present
    update_cache: true
  when: jenkins_repo_url | default(false)
  tags: ['skip_ansible_lint']

- name: Ensure Jenkins is installed.
  apt:
    name: jenkins
    state: "{{ jenkins_package_state }}"
  notify: configure default users